const visualArchive = [
  {
    id: 1,
    title: "Moviq",
    size: "md:col-span-2 md:row-span-2",
    img: "/projects/moviq/moviq-dashboard-operations-system.webp",
    tag: "SOFTWARE",
    desc: "Custom operations software for a moving company, replacing spreadsheets, chats, and manual coordination with structured workflows.",
    href: "/projects/moviq",
    hrefLabel: "Open_Project",
    linkType: "internal",
  },
  {
    id: 2,
    title: "Bronzora_System",
    size: "md:col-span-1 md:row-span-1",
    img: "/projects/bronzora/bronzora-studio-homepage-hero-metal-clay-workshops.webp",
    tag: "PLATFORM",
    desc: "Content, booking, and SEO system built for a studio business with structured growth and rule-based scheduling.",
    href: "/projects/bronzora",
    hrefLabel: "Open_Project",
    linkType: "internal",
  },
  {
    id: 3,
    title: "Local_Service_Framework",
    size: "md:col-span-1 md:row-span-1",
    img: "/projects/movers-network/los-angeles-moving-company-homepage-hero.webp",
    tag: "FRAMEWORK",
    desc: "Reusable multi-city SEO and lead generation system deployed across real local service websites.",
    href: "/projects/local-service-framework",
    hrefLabel: "Open_Project",
    linkType: "internal",
  },
  {
    id: 4,
    title: "Agency_Landing_System",
    size: "md:col-span-1 md:row-span-1",
    img: "/projects/agency-landing/agency-landing-paid-traffic-hero.webp",
    tag: "FUNNEL",
    desc: "Landing page, tracking, and GHL integration system built for paid traffic campaigns and agency lead flow.",
    href: "/projects/landing-page-ghl-integration",
    hrefLabel: "Open_Project",
    linkType: "internal",
  },
  {
    id: 5,
    title: "System_Archive",
    size: "md:col-span-1 md:row-span-1",
    img: "/archive/archive-cover.jpg",
    tag: "ARCHIVE",
    desc: "Browse flagship systems, rebuilds, frameworks, and technical records across Lecobyte projects.",
    href: "/archive",
    hrefLabel: "Open_Archive",
    linkType: "internal",
  },
] as const;

export default visualArchive;